### ISSUE TITLE
GPU Memory Usage

### ISSUE THREAD

**Issue by tchittesh** [lxasqjc/Deformation-Segmentation#10]
What GPUs did you train on and how much memory did your experiments require? I'm trying to use standard 12 GB RTX 2080Ti's with no luck. For reference, I'm able to train DeepGlobes up to 275x275 with a batch size of 1 on 4 GPUs, but am unable to run the normal 300x300 size. 

Also wondering if you have any intuition for what operations demand this much memory? For what it's worth, this seems VERY memory intensive.

**Comment by lxasqjc** [comment]
Hi @tchittesh, thanks for your question.
Yes you are right downsample to 300x300 does cost much more, and I run my experiment with 4 x 24GB rtx6000 with a batch size of 1 or 2 x 48GB rtx8000 with a batch size of 2.

The reason for high memory consumption is the segmentation backbone we used is HRnet without staged downsampling (a typical operation of many SoTA segmentation networks to reduce computation cost). But here as we already learn to downsample, hence we removed the downsampling operation. If you use a standard segmentation network which includes e.g. 8x downsampling the memory consumption should be low.
