### ISSUE TITLE
Question about deform_pretrain[_bol]

### ISSUE THREAD

**Issue by tchittesh** [lxasqjc/Deformation-Segmentation#12]
Sorry to spam issues haha just have a lot of questions. And thanks for releasing your codebase! It's really helpful for our research.

It seems these flags are referenced twice. Once here, where the low resolution image gets blurred if the epoch is less than `cfg.TRAIN.deform_pretrain`
https://github.com/lxasqjc/Deformation-Segmentation/blob/8df517746f53a2bec825b7939e7f56b792600b6c/models/models.py#L405-L409

and here, where the sampled image gets blurred if `not self.cfg.TRAIN.deform_pretrain_bol` (this flag is set to True, so the sampled image never gets blurred)
https://github.com/lxasqjc/Deformation-Segmentation/blob/8df517746f53a2bec825b7939e7f56b792600b6c/models/models.py#L511-L517

So my questions are twofold. 
1. What's the intuition behind blurring the low resolution image (which is only used to generate saliency) for the first 100 epochs?
2. Why doesn't the sampled image get blurred for the first 100 epochs? I thought this was the trick from Learning to Zoom. Do you not need it in practice?

**Comment by lxasqjc** [comment]
Hi @tchittesh, thanks for your question:

- blurring the low resolution was implemented simply to consistently apply this trick, however maybe you are right there is no point, but I haven't tested;
- from my practice, this is an important trick to apply, the intuition is like a wamp up stage to avoid degenerate solution/ local minimal, and this is achieved by regularising the pixel-wise task is by smoothing during the pretrain stage.
