### ISSUE TITLE
seg loss and edge loss is NAN

### ISSUE THREAD

**Issue by tjdhg456** [lxasqjc/Deformation-Segmentation#2]
I have one more question.

When I run the 'quick_start_bash/cityscape_64_128_ours.sh' (w/o any change) , seg loss and edge loss shows NaN value.
Can you check?

Thank you for your awesome work.

**Comment by twangnh** [comment]
same here, have you solved the problem? thanks

**Comment by twangnh** [comment]
@lxasqjc could you please give some illustration?

```
Epoch 2 edge_loss_scale=100.0
Scaled Edge loss: nan

seg loss: 0.4372396767139435, scaled edge_loss: nan

seg loss: 0.4372396767139435, scaled edge_loss: nan 
```

**Comment by tjdhg456** [comment]
In my case, I fixed the directory structures of the Cityscapes dataset.

**Comment by tjdhg456** [comment]
![image](https://user-images.githubusercontent.com/52290290/185024392-28fc127c-85d5-41fb-8c41-c0dbd7045b8f.png)

The images' paths in the list of "~.odgt" files are different with the data path.

**Comment by twangnh** [comment]
@tjdhg456 thanks! same problem with me, fixed now

**Comment by lxasqjc** [comment]
Thank you both for working out this issue!
Could you share one example of your fixed data path, and I can update it in case others have the same problem?

_PS: I think it's because I removed the city subfolders and put all images under one folder 
(e.g. "images/training/tubingen_000025_000019_leftImg8bit.png" instead of "images/training/tubingen/000025_000019_leftImg8bit.png"), is this the case?_

**Comment by tjdhg456** [comment]
Hi! 

Right. In my case, adding the city subfolders to .odgt files makes it work.

Again, thank you for your great work.
It is very helpful research.

**Comment by lxasqjc** [comment]
> Hi!
> 
> Right. In my case, adding the city subfolders to .odgt files makes it work.
> 
> Again, thank you for your great work. It is very helpful research.

That's great, I'll add a note, thank you for sharing!

**Comment by tchittesh** [comment]
For those wondering add subfolders to the .odgt files easily, if you happen to use VSCode, finding `([a-z]*)_(\d{6}_\d{6})` with regex enabled and replacing with `$1/$1_$2` works.

**Comment by xsk07** [comment]
We are getting the same issue, we checked our paths and they seem correct, this is a visualization of the val phase:

![126796_sat](https://user-images.githubusercontent.com/87577593/207854623-5dea0eb1-7cbc-4215-927f-d2b10ab381c0.png)

**Comment by lxasqjc** [comment]
> We are getting the same issue, we checked our paths and they seem correct, this is a visualization of the val phase:
> 
> ![126796_sat](https://user-images.githubusercontent.com/87577593/207854623-5dea0eb1-7cbc-4215-927f-d2b10ab381c0.png)
> 
> Anyone has an idea what can be wrong?

Are you getting nan with the [default config](https://github.com/lxasqjc/Deformation-Segmentation/blob/main/config/deform-deepglob.yaml)?

**Comment by xsk07** [comment]
Thank you, now with the default confing it works! Yes we have changed the config file, more precisely the batch size to 1 because of another error that raised up during the execution.

**Comment by lxasqjc** [comment]
That's great! Yes, potentially with batch size of 1 the model may collapse to local minimal (salient to a easy location), I think that's the reason.
