### ISSUE TITLE
pretraining trick error in the code

### ISSUE THREAD

**Issue by joihn** [lxasqjc/Deformation-Segmentation#22]
`p` is either 0 or 1
https://github.com/lxasqjc/Deformation-Segmentation/blob/main/models/models.py#L515

random.random() output is [0,1]

therefore
https://github.com/lxasqjc/Deformation-Segmentation/blob/main/models/models.py#L515
```
        if random.random() > p:
            min_saliency_len = min(self.input_size)
            s = random.randint(min_saliency_len // 3, min_saliency_len)
            x_sampled = nn.AdaptiveAvgPool2d((s, s))(x_sampled)
            x_sampled = nn.Upsample(size=self.input_size_net, mode='bilinear')(x_sampled)
```
Will NEVER get executed

**Comment by lxasqjc** [comment]
when p is 0 and random.random() > 0 it will execute

**Comment by joihn** [comment]
my bad I misread the sign, and would have expected a random function whose output is not [0,1] in this scenario,
thank you for the fast answer
