### ISSUE TITLE
 open source question

### ISSUE THREAD

**Issue by sori1234** [lxasqjc/Deformation-Segmentation#3]
- The train_fove.py file does not exist. Where are you?

- Should I create the directory tree folder myself?

**Comment by lxasqjc** [comment]
Thanks for your comments:
- "train_fove.py" is a typo and it should be "train_deform.py", which is corrected in commit [d59bdf1](https://github.com/lxasqjc/Deformation-Segmentation/commit/d59bdf17b3b17735b6105742acf50bc344ff517f).
- Yes please create the directory tree following the structure specified in [Data preparation](https://github.com/lxasqjc/Deformation-Segmentation/commit/d59bdf17b3b17735b6105742acf50bc344ff517f).
