### ISSUE TITLE
How to reproduce the intrinsic mIoU value?

### ISSUE THREAD

**Issue by tjyuyao** [lxasqjc/Deformation-Segmentation#5]
Dear Chen,

I am not able to reproduce a simple uniform intrinsic mIoU baseline metric of 0.78 on CityScapes downsampled to 64x128 from 1024x2048 (Figure 4(a) from paper). Do you downsample & upsample the GT map with nearest uniform sampler and measure mIoU? I can't really tell the steps by reading the code. I get 0.74 by doing so in a script written from scratch.

Best,
Yuyao

**Comment by lxasqjc** [comment]
Hi Yuyao, 

Apology for the late reply. For the uniform baseline, bilinear interpolation is applied to obtain a more robust baseline. 

Best
Chen
