### ISSUE TITLE
the implementation of create_grid function

### ISSUE THREAD

**Issue by twangnh** [lxasqjc/Deformation-Segmentation#7]
Hi @lxasqjc , Could you please give some illustration of the create_grid function, specifically, could you give some comments on the following lines, and why there is a grid_y ? Thanks!

```
        if len(self.input_size_net_eval) != 0 and segSize is not None:# inference
            grid = nn.Upsample(size=self.input_size_net_infer, mode='bilinear')(grid)
        else:
            grid = nn.Upsample(size=self.input_size_net, mode='bilinear')(grid)
        if segSize is None:# training
            grid_y = nn.Upsample(size=tuple(np.array(self.input_size_net)//self.cfg.DATASET.segm_downsampling_rate), mode='bilinear')(grid)
        else:# inference
            grid_y = nn.Upsample(size=tuple(np.array(self.input_size_net_infer)), mode='bilinear')(grid)

```

**Comment by lxasqjc** [comment]
Hi @twangnh, I have commented on the create_grid function, see [8df5177](https://github.com/lxasqjc/Deformation-Segmentation/commit/8df517746f53a2bec825b7939e7f56b792600b6c).
The grid_y is for downsampling label y, to handle segmentation architectures whose predictions are not same size with input x. But in the published work, grid_y is the same as the grid which is for downsampling input x.
Hope it helps :)
